# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-UK"
title: "TEN"
subtitle: "The Final Network - a TEE-native encrypted Ethereum Layer 2 for the new internet."
description: "TEN is an Ethereum-equivalent confidential smart contract L2 network."
url: "https://ten.xyz"
name: "TEN"
repository: "ten-protocol/obscuro.github.io"
search: true
logo: "/assets/images/favicon-32x32.png"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-titles-from-headings
  - jekyll-relative-links
  
titles_from_headings:
  strip_title: true
  
atom_feed:
  hide: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: "pages"
      layout: single
      author_profile: false
      strip_title: true
      classes: wide
      toc: false

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/tenprotocol"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ten-protocol"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XL6VWGQK1P"
