# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-UK"
title: "Obscuro"
subtitle: "Ethereum-compatible confidential smart contract L2 network."
description: "Obscuro is an Ethereum-compatible confidential smart contract L2 network."
url: "https://obscu.ro"
name: "Obscuro"
repository: "corda/obscuro.github.io"
search: true

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-titles-from-headings
  - jekyll-relative-links
  
titles_from_headings:
  strip_title: true
  
atom_feed:
  hide: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: "pages"
      layout: single
      author_profile: true
      strip_title: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/0xScuro"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/corda/obscuro"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XL6VWGQK1P"